### ISSUE TITLE
Tickle Watchdog to prevent reboot after 7 seconds

### ISSUE THREAD

**Issue by lupyuen** [lupyuen/pinetime-rust-mynewt#28]
Hi @caspermeijn with reference to...

https://github.com/apache/mynewt-core/pull/2381/files

I'm now testing the new Sanity Interval, but using the old Watchdog Interval...

https://github.com/lupyuen/pinetime-rust-mynewt/blob/lvgl/apps/my_sensor_app/syscfg.yml#L119-L127

```
syscfg.vals:

    ###########################################################################
    # Watchdog Settings

    # The default PineTime bootloader will setup a 7 second watchdog
    SANITY_INTERVAL:      5000  #  Tickle the watchdog every 5 seconds, that the watchdog won't trigger a reboot
    # WATCHDOG_INTERVAL:  7000  #  If watchdog is not set, set it to 7 seconds
```

Note that I'm updating the apps/syscfg.yml, not the bsp/syscfg.yml.

This seems to work, PineTime is responding to BLE after 7 seconds. Previously it was hanging due to the watchdog being triggered.

So I suppose this validates your proposed fix for SANITY_INTERVAL.

Do we need to change WATCHDOG_INTERVAL? Or just leave it as default for now?  Thanks.

**Comment by caspermeijn** [comment]
You are right, only the SANITY_INTERVAL is needed to make the application work properly. However I liked the fact that the application tries to configure the watchdog the same as the bootloader. This way you have the same watchdog behaviour when running without bootloader, which could ease problem searching. 
And there is no harm is setting WATCHDOG_INTERVAL, so why not?
Maybe the bootloader could even use the value from WATCHDOG_INTERVAL.

**Comment by caspermeijn** [comment]
I found this: https://github.com/JuulLabs-OSS/mcuboot/blob/10c97baa77d8b6b75b0411d2c55c497c43af0f0f/boot/mynewt/src/main.c#L221

MCUBoot will automatically init the watchdog when WATCHDOG_INTERVAL is set. So you either need to set WATCHDOG_INTERVAL or https://github.com/lupyuen/pinetime-rust-mynewt/blob/b3fb1d9c6bf6b4f81f89dd61758765ea14a7bfb1/libs/pinetime_boot/src/pinetime_boot.c#L132, but not both.

So I think it would make sense to switch over to using WATCHDOG_INTERVAL and removing the setup_watchdog() function.

**Comment by lupyuen** [comment]
pinetime-rust-mynewt has been revamped as educational firmware (so it's not meant for daily use). The following config should be sufficient for educational purposes: 

https://github.com/lupyuen/pinetime-rust-mynewt/blob/master/apps/my_sensor_app/syscfg.yml

```yaml
syscfg.vals:

    ###########################################################################
    # Watchdog Settings

    # The default PineTime bootloader will setup a 7 second watchdog
    SANITY_INTERVAL:      5000  #  Tickle the watchdog every 5 seconds, that the watchdog won't trigger a reboot
    # WATCHDOG_INTERVAL:  7000  #  If watchdog is not set, set it to 7 seconds
```

Also refer to this note...

https://lupyuen.github.io/pinetime-rust-mynewt/articles/mcuboot#bootloader-watchdog
